### ISSUE TITLE
Support go1.19

### ISSUE THREAD

**Issue by chenrui333** [shadowsocks/v2ray-plugin#292]
Have some runtime failure with go1.19

```
==> Testing v2ray-plugin
panic: panic: qtls.CertificateRequestInfo doesn't matchqtls.CertificateRequestInfo doesn't match

goroutine
1 [running]:

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
	github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17github.com/marten-seemann/qtls-go1-16.init.0 +(0x190)

	github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x190
```

Same with go1.18

relates to https://github.com/Homebrew/homebrew-core/pull/110036

**Comment by chenrui333** [comment]
needs quic-go upgrade.

**Comment by kimw** [comment]
Yes, it's a good idea to upgrade to go1.19 since the current *stable versions* are only go 1.19.1 & 1.18.6, others (including go1.16) are *archived* (AKA not stable).

Golang archived versions are not maintained versions especially secure updates.
