### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by LiveChief** [shadowsocks/v2ray-plugin#4]
```
root@demo-server:/# cd v2ray-plugin/
root@demo-server:/v2ray-plugin# go get
go get: no install location for directory /v2ray-plugin outside GOPATH
        For more details see: 'go help gopath'
root@demo-server:/v2ray-plugin# go get
go get: no install location for directory /v2ray-plugin outside GOPATH
        For more details see: 'go help gopath'
root@demo-server:/v2ray-plugin# go build
# _/v2ray-plugin
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64e3d5, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc014000000, 0x4000000, 0x7feff8)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x7e6580, 0x4000000, 0x7fb851972248, 0xc000041e58)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x7e6580, 0x26, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x7e6580, 0x26, 0x7ff008, 0x20300400000000)
        /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x7e6580, 0x26, 0x410101, 0x7fb851bdbb00)
        /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x7e6580, 0x26, 0xc000000101, 0x415785)
        /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x4c000, 0x450100, 0x7fb85474d000)
        /usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc004ba0830 sp=0xc004ba0828 pc=0x454d20
runtime.mallocgc(0x4c000, 0x0, 0xc004ba0900, 0x4b583b)
        /usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc004ba08d0 sp=0xc004ba0830 pc=0x40bb56
runtime.growslice(0x5ff800, 0xc013f9a000, 0x3bfef, 0x3c000, 0x3c0d9, 0x0, 0x0, 0xc000056680)
        /usr/lib/go-1.11/src/runtime/slice.go:197 +0x219 fp=0xc004ba0938 sp=0xc004ba08d0 pc=0x4404d9
cmd/link/internal/ld.putelfstr(0xc0087c40f0, 0xea, 0x649788)
        /usr/lib/go-1.11/src/cmd/link/internal/ld/symtab.go:51 +0x1b7 fp=0xc004ba09a8 sp=0xc004ba0938 pc=0x58ece7
cmd/link/internal/ld.putelfsym(0xc0004d8000, 0xc008796c60, 0xc0087c40f0, 0xea, 0x7feb44, 0xc2eb40, 0x0)
        /usr/lib/go-1.11/src/cmd/link/internal/ld/symtab.go:191 +0x205 fp=0xc004ba0a58 sp=0xc004ba09a8 pc=0x58f0b5
cmd/link/internal/ld.genasmsym(0xc0004d8000, 0x659108)
        /usr/lib/go-1.11/src/cmd/link/internal/ld/lib.go:2091 +0x3cb fp=0xc004ba0b78 sp=0xc004ba0a58 pc=0x57872b
cmd/link/internal/ld.Asmelfsym(0xc0004d8000)
        /usr/lib/go-1.11/src/cmd/link/internal/ld/symtab.go:220 +0x108 fp=0xc004ba0bc0 sp=0xc004ba0b78 pc=0x58f8b8
cmd/link/internal/amd64.asmb(0xc0004d8000)
        /usr/lib/go-1.11/src/cmd/link/internal/amd64/asm.go:774 +0x758 fp=0xc004ba0ce8 sp=0xc004ba0bc0 pc=0x59f9a8
cmd/link/internal/ld.Main(0x7d3c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64ff8f, 0x1b, 0x64d0be, 0x14, ...)
        /usr/lib/go-1.11/src/cmd/link/internal/ld/main.go:237 +0xbeb fp=0xc004ba0e80 sp=0xc004ba0ce8 pc=0x58480b
main.main()
        /usr/lib/go-1.11/src/cmd/link/main.go:65 +0x227 fp=0xc004ba1f98 sp=0xc004ba0e80 pc=0x5dd1a7
runtime.main()
        /usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc004ba1fe0 sp=0xc004ba1f98 pc=0x42bb87
runtime.goexit()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc004ba1fe8 sp=0xc004ba1fe0 pc=0x456c81
root@demo-server:/v2ray-plugin# 
```

**Comment by madeye** [comment]
As the log suggested, your server is out of memory.

**Comment by LiveChief** [comment]
32GB ram.

**Comment by LiveChief** [comment]
Had to reinstall the OS and it was kinda fixed i guess...

```
root@demo-server:/# ss-server  -s 0.0.0.0 -p 443 -l 1080 -k password -m aes-256-gcm --plugin v2ray-plugin --plugin-opts "server;tls"
 2019-01-15 05:53:31 INFO: plugin "v2ray-plugin" enabled
 2019-01-15 05:53:31 INFO: initializing ciphers... aes-256-gcm
 2019-01-15 05:53:31 INFO: tcp server listening at 127.0.0.1:48865
 2019-01-15 05:53:31 INFO: running from root user
Permission denied
 2019-01-15 05:53:31 ERROR: plugin service exit unexpectedly
```

```
username@demo-server:~$ ss-server  -s 0.0.0.0  -p 443 -l 1080 -k password -m aes-256-gcm --plugin v2ray-plugin --plugin-opts "server;tls"
 2019-01-15 05:56:11 INFO: plugin "v2ray-plugin" enabled
 2019-01-15 05:56:11 INFO: initializing ciphers... aes-256-gcm
 2019-01-15 05:56:11 INFO: tcp server listening at 127.0.0.1:53235
No such file or directory
 2019-01-15 05:56:11 ERROR: plugin service exit unexpectedly
```

**Comment by madeye** [comment]
First error is `Permission denied", second is "No such file or directory".

Make sure the executable is built successfully.

**Comment by madeye** [comment]
Also, to enable TLS, you need a valid cert file.

**Comment by buguniaogu** [comment]
failed to parse config > main: failed to read cert > open /root/.acme.sh/cloudfront.com/fullchain.cer: no such file or directory
How can change default file/directory?
I use certbot to install cert.....it's /etc/letsencrypt/live/www.example000.com/fullchain.pem
thanks..

**Comment by madeye** [comment]
Add this into `plugin-opts`: `cert=/etc/letsencrypt/live/www.example000.com/fullchain.pem`

**Comment by LiveChief** [comment]
> Add this into `plugin-opts`: `cert=/etc/letsencrypt/live/www.example000.com/fullchain.pem`

please explain a little bit more, this is simple yet complicated, i didn't actually read though the source nor much familiar with v2ray but it seems like we need a real certificate and a web server for HTTPS traffic..

can u please update the read me instructions

**Comment by LiveChief** [comment]
Hey @madeye I have a question so let's so let's say I want to enable tls with let's encrypt, do I have to setup Apache with it or just install let's encrypt via running certbot, also do I do 

--plugin-opts "server;tls"

Or 

plugin-opts: cert=/etc/letsencrypt/live/www.example000.com/fullchain.pem

**Comment by Mygod** [comment]
See [here](https://github.com/shadowsocks/shadowsocks-org/issues/139#issuecomment-454369731) for example to set it up behind an HTTP server (in this case Caddy). To use it without http server, you need to supply both `cert` (fullchain) and `key` (private key).

**Comment by ziruizhuang** [comment]
Run into similar error message here. Using the release from github v1.2.0. 

```
~# sudo ss-server -s 0.0.0.0 -s :: -p 8888 -k 12345678 -m chacha20 --fast-open -u  --reuse-port --plugin v2ray-plugin --plugin-opts "server" -v
 2019-10-10 13:00:01 INFO: using tcp fast open
 2019-10-10 13:00:01 INFO: plugin "v2ray-plugin" enabled
 2019-10-10 13:00:01 INFO: UDP relay enabled
 2019-10-10 13:00:01 INFO: initializing ciphers... chacha20
 2019-10-10 13:00:01 INFO: tcp server listening at 127.0.0.1:55847
 2019-10-10 13:00:01 INFO: tcp port reuse enabled
 2019-10-10 13:00:01 INFO: udp server listening at 0.0.0.0:8888
 2019-10-10 13:00:01 INFO: udp port reuse enabled
 2019-10-10 13:00:01 INFO: udp server listening at [::]:8888
 2019-10-10 13:00:01 INFO: udp port reuse enabled
 2019-10-10 13:00:01 INFO: running from root user
Permission denied
 2019-10-10 13:00:01 ERROR: plugin service exit unexpectedly
 2019-10-10 13:00:01 INFO: closed gracefully
 2019-10-10 13:00:01 INFO: error on terminating the plugin.
```
